dev:
    image: cajan2/zhihu_spider
    command: cd /zhihu_spider/zhihu/ && service rabbitmq-server start && celery -A zhihu.tools.async worker --loglevel=info
    volumes:
        - ./:/zhihu_spider
        - ../data:/data/db
    ports:
        - "20000:27017"
        - "20001:5672"
    privileged: true
    tty: true
    stdin_open: true
    restart: always
